travis:
  secure:
    BINSTAR_TOKEN: d5jH2gOo4cUXQBF7XaDVWH5IbmsBoowFWriM9oC9r74WKCxLtBVZy25yE3QWdICuSZYov3XTd54rtx+//VVcROEk2dbsNUuiRI12eOEnr/GpueN7XeXVLb/f3OKuWKDFRD1Y4zZGa4q1VZXAlMvM262QeWEeceo5LXD8NejvHaXDV2HhGLlqKMOqepZdr1xke5HuNiIchsy7djgoIfu+efESuIBWt9JejBeDb4xVyk5zlfhaeoni1+nTCvG1iGs6KSadbsm0PXYFM7FvJAGLujkIiZtbpIiHZxTBJ14c/65HZSlO5F5Ye5+PgMKCZ8q96/4lzbIeMqMcsFXY8EfA6EuAXwjl0cCo0sm/Qw8QWYqysssBLGd7Hn1UVgehMgdJaBShcJf5WCmRXduH+4iy0/lDeQnWlpjXe3lWymIGVViLDWfmofRoERHkTiNtwl1OWxGLZ916lqV6+kT1oVv7c2jLiTabJ7i/BTT212GFtTIduTRgSwaRR7SQsHhAfY2nbDVMOT8OBSHQO8LOhdeobScQfXx5Ama30qLLpHWXCJXGv+ehlcNCcS1h1tjoH8Y0/TnuNpAWKhETvJ31quBjP6D9hRWuKsaAvgW1OOFPdQP9XAsp+FmzlFvVSbmZMiUw5jCE90SoB17Plm8HeIxwwNZNnp//rCDW75FJvC01pN0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
